inherit_gem:
  main_branch_shared_rubocop_config: config/rubocop.yml

inherit_mode:
  merge:
    - Exclude

Naming/FileName:
  Exclude:
    - 'lib/yard-doctest.rb'

Metrics/ClassLength:
  Max: 150

Style/DocumentDynamicEvalDefinition:
  Exclude:
    - 'lib/yard/doctest/example.rb'

# Allow test data to have long lines
Layout/LineLength:
  Exclude:
    - "*.gemspec"

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"

AllCops:
  TargetRubyVersion: 3.3
