inherit_gem:
  main_branch_shared_rubocop_config: config/rubocop.yml

inherit_mode:
  merge:
    - Exclude

Naming/FileName:
  Exclude:
    - 'lib/yard-doctest.rb'

Style/DocumentDynamicEvalDefinition:
  Exclude:
    - 'lib/yard/doctest/example.rb'

# Allow test data to have long lines
Layout/LineLength:
  Exclude:
    - "*.gemspec"

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"

AllCops:
  # Pin this project to Ruby 3.1 in case the shared config above is upgraded to 3.2
  # or later.
  TargetRubyVersion: 3.3
